export default function PrivacyPage() {
  return (
    <main className="legal-page">
      <div className="legal-shell">
        <div className="page-kicker">Suvacya · Privacy</div>
        <h1>Suvacya Privacy Policy</h1>
        <p className="legal-meta">Effective date: 29 September 2026 · Last updated: 29 September 2026</p>

        <h2>1. Who we are</h2>
        <p>Suvacya ("Suvacya", "we", "us" or "our") is operated by <strong>Kanishka Utsav</strong> as a sole proprietorship in Maharashtra, India. Suvacya is not currently incorporated as a separate company.</p>
        <p><strong>Privacy / Data Protection Contact:</strong> Kanishka Utsav · <a href="mailto:kanishka.utsav@gmail.com">kanishka.utsav@gmail.com</a></p>

        <h2>2. Who may use Suvacya</h2>
        <p>Suvacya is intended only for individuals who are at least 18 years old. By creating or using an account, you represent that you are at least 18 and have the legal capacity to use the service. Suvacya does not knowingly provide accounts to individuals under 18.</p>

        <h2>3. Availability and international processing</h2>
        <p>Suvacya may be made available worldwide. Access is currently limited to users who have been whitelisted or otherwise expressly permitted to use the service. Because the service uses international infrastructure and third-party providers, information may be processed in countries other than where you live. We apply safeguards required by applicable law for such processing.</p>

        <h2>4. Information we process</h2>
        <ul>
          <li>Account and authentication information, including name and email address.</li>
          <li>LinkedIn information made available through LinkedIn APIs after you authorize the connection, including eligible professional profile information and eligible LinkedIn content permitted by the applicable scopes and terms.</li>
          <li>Professional information and eligible LinkedIn past posts used to create and maintain your personalized Brand DNA.</li>
          <li>Brand DNA, preferences, drafts, edits, feedback, approvals, rejections, research requests and generated content.</li>
          <li>User-specific learning signals from your interactions with Suvacya, used to improve future results for your own account.</li>
          <li>Technical, security and operational information such as session information, timestamps, request information, error information and security logs generated by the service.</li>
        </ul>

        <h2>5. How we use information</h2>
        <p>We use information to provide, operate, maintain and secure Suvacya; authenticate accounts; connect to LinkedIn after authorization; create and maintain personalized Brand DNA; generate and refine content; provide research features; learn from your interactions to improve results for the same account; detect abuse and security incidents; troubleshoot reliability issues; and comply with applicable legal obligations.</p>

        <h2>6. LinkedIn connection</h2>
        <p>When you connect LinkedIn, Suvacya accesses only information made available through the authorized LinkedIn APIs and permissions. Suvacya does not request your LinkedIn password. Eligible LinkedIn information is used to provide the features you request, including Brand DNA, research and content workflows.</p>
        <p>You can disconnect LinkedIn without deleting your Suvacya account. Account deletion deletes applicable LinkedIn API data and authentication tokens associated with your account as required by applicable law and LinkedIn's applicable API terms, subject to narrow legal or security exceptions.</p>

        <h2>7. User-specific learning</h2>
        <p>Suvacya may learn from your feedback, edits, approvals, rejections, interactions and content preferences to improve future results for your account. This user-specific learning is not intended to personalize another user's results. Suvacya does not use your content to train a general-purpose AI model operated by Suvacya, and does not use your content for marketing.</p>

        <h2>8. Third-party AI and technology providers</h2>
        <p>Suvacya uses third-party AI and technology providers, including Groq, OpenRouter and Google Gemini, for certain features. Depending on the feature and routing path, relevant user-provided content, professional context, Brand DNA context, research requests and instructions may be transmitted to and processed by those providers.</p>
        <p>Third-party providers operate under their own contractual, privacy and data-handling terms. Suvacya's statement that it does not itself train a general-purpose AI model on your content is not a blanket representation that every third-party provider or every provider endpoint has identical retention or model-improvement practices. Provider configuration and routing are maintained to limit unnecessary disclosure and to use the minimum context reasonably required for the requested feature.</p>
        <p>If a material change to third-party processing affects this policy, Suvacya will update this notice as required.</p>

        <h2>9. Sharing and disclosure</h2>
        <p>Information may be disclosed to service providers that help operate requested features, including infrastructure, hosting, database, authentication, security, observability and AI providers; to professional advisers or authorities where legally required; or in a lawful business transfer subject to applicable safeguards. Suvacya does not sell your personal information and does not use your content for marketing.</p>

        <h2>10. Retention</h2>
        <p>Suvacya follows a purpose-based retention approach and retains information for no longer than reasonably necessary to provide the service, maintain security, investigate abuse or comply with applicable legal obligations.</p>
        <ul>
          <li>Account and Brand DNA information: while your account is active and as necessary to provide the service.</li>
          <li>LinkedIn API data and tokens: only as necessary for the authorized functionality and as required by applicable LinkedIn terms, with deletion on disconnect or account deletion where applicable.</li>
          <li>Drafts, generated content, research history and user-specific learning: while needed for the service and until account deletion, subject to lawful exceptions.</li>
          <li>Operational and security records: for the shortest period reasonably necessary for security, troubleshooting and compliance.</li>
          <li>Backups: according to the applicable backup lifecycle rather than indefinite retention.</li>
          <li>Legally required records: only for the minimum period required for the applicable obligation.</li>
        </ul>

        <h2>11. Account deletion</h2>
        <p>You may permanently delete your Suvacya account through the available product control or by contacting <a href="mailto:kanishka.utsav@gmail.com">kanishka.utsav@gmail.com</a>. Account deletion is intended to delete your profile, Brand DNA, drafts, research history, user-specific learning data and applicable LinkedIn API data and tokens.</p>
        <p>Limited information may be retained where necessary to comply with law, establish or defend legal claims, prevent fraud or abuse, or maintain essential security records. Deletion from active systems and propagation through backups may not be instantaneous.</p>

        <h2>12. Your rights and choices</h2>
        <p>Depending on where you live and which laws apply, you may have rights to access, correct or delete personal information, withdraw consent where processing is based on consent, and raise a complaint or grievance. Contact Kanishka Utsav at <a href="mailto:kanishka.utsav@gmail.com">kanishka.utsav@gmail.com</a>. We may need to verify your identity before completing a request.</p>

        <h2>13. Security</h2>
        <p>Suvacya uses technical and organizational measures intended to protect information against unauthorized access, alteration, disclosure, loss and misuse. No internet service can guarantee absolute security. Where an incident triggers a legal notification obligation, we will follow the applicable requirements.</p>

        <h2>14. Cookies and similar technologies</h2>
        <p>Suvacya may use essential cookies, local storage or similar mechanisms required for authentication, session management, security and core functionality. If non-essential analytics or tracking technologies are introduced, this policy will be updated and any required controls or consent will be provided.</p>

        <h2>15. Changes</h2>
        <p>We may update this Privacy Policy as the service, law, providers or data practices change. Material changes will be communicated through the service or another appropriate mechanism where required by law.</p>

        <h2>16. Contact</h2>
        <p><strong>Kanishka Utsav</strong><br/>Privacy / Data Protection Contact<br/><a href="mailto:kanishka.utsav@gmail.com">kanishka.utsav@gmail.com</a><br/>Maharashtra, India</p>
        <p><a href="/terms">Terms of Service</a> · <a href="/">Back to Suvacya</a></p>
      </div>
    </main>
  );
}
